/**
 * Centralized user-facing strings for LifeTrack Pro.
 * Adheres strictly to the rule of no hardcoded strings in components.
 */

export const STRINGS = {
  common: {
    appName: 'LifeTrack Pro',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    complete: 'Complete',
    add: 'Add',
    reschedule: 'Reschedule',
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    empty: 'No items found',
    back: 'Back',
    next: 'Next',
    confirm: 'Confirm',
    start: 'Start',
    pause: 'Pause',
    resume: 'Resume',
    reset: 'Reset',
    dismiss: 'Dismiss',
    hours: 'hours',
    days: 'days',
    streak: 'streak',
    xp: 'XP',
    level: 'Lvl',
  },

  auth: {
    title: 'Enter the Calm Workspace',
    subtitle: 'Track goals, manage syllabus, and build deep focus in one minimalist application.',
    emailPlaceholder: 'Enter your email address',
    sendCode: 'Send Secure OTP',
    verifyTitle: 'Verify Your OTP',
    verifySubtitle: 'We sent a 6-digit confirmation code to your email address.',
    otpPlaceholder: 'Enter 6-digit OTP',
    verifyBtn: 'Verify and Sign In',
    sending: 'Sending code...',
    verifying: 'Verifying code...',
    backToLogin: 'Back to email entry',
  },

  onboarding: {
    step1: {
      title: 'Define Your Purpose',
      subtitle: 'Select the primary identity that reflects your focus area.',
      categories: {
        student: 'Student',
        employee: 'Employee / Corporate',
        creator: 'Creator / Freelancer',
        entrepreneur: 'Entrepreneur',
        educator: 'Educator',
        aspirant: 'Aspirant',
      },
    },
    step2: {
      studentTitle: 'Which Exam Are You Preparing For?',
      studentSubtitle: 'Select all exams that apply to optimize your syllabus structures.',
      employeeTitle: 'What is Your Work Environment?',
      employeeSubtitle: 'Select your workspace context to structure custom personal blocks.',
      creatorTitle: 'What Type of Content Do You Build?',
      creatorSubtitle: 'Help us customize your idea capture and posting milestones.',
      studentExams: {
        neet: 'NEET',
        jee: 'JEE',
        upsc: 'UPSC',
        ssc: 'SSC',
        cat: 'CAT',
        gate: 'GATE',
        clat: 'CLAT',
        other: 'Other Exam',
      },
      employeeRoles: {
        corporate: 'Corporate (9-to-5)',
        startup: 'Startup (Fast-paced)',
        government: 'Government Sector',
        remote: 'Remote / WFH',
      },
      creatorTypes: {
        youtuber: 'YouTuber / Video',
        blogger: 'Writer / Blogger',
        designer: 'Designer / Artist',
        developer: 'Developer / Indie Hacker',
        other: 'Other Creator',
      },
    },
    step3: {
      title: 'Set Your Primary Milestone',
      subtitle: 'What is the absolute single major objective you want to achieve?',
      placeholder: 'I want to crack UPSC and clear IAS in first attempt / build an indie software...',
      timelineLabel: 'Select Your Target Timeline',
      timelines: {
        threeMonths: '3 Months',
        sixMonths: '6 Months',
        oneYear: '1 Year',
        twoYears: '2 Years',
        fiveYears: '5 Years',
      },
      dateLabel: 'Set Deadline Target Date',
    },
    step4: {
      title: 'Allocate Daily Focus Hours',
      subtitle: 'Be realistic. How many focus hours will you commit each day?',
      hoursDialLabel: 'Hours per day',
      peakTimeLabel: 'When is your peak cognitive energy?',
      peakTimes: {
        morning: 'Morning (Deep Focus)',
        afternoon: 'Afternoon (Steady Pace)',
        night: 'Night (Quiet Sessions)',
      },
    },
    step5: {
      title: 'Your Calm Workspace is Ready',
      subtitle: 'Confirm your focus blueprint and begin your life operating system.',
      categoryLabel: 'Primary Segment',
      goalLabel: 'Your Moonshot Goal',
      deadlineLabel: 'Target Deadline',
      hoursLabel: 'Focus Commitment',
      peakLabel: 'Peak Energy Peak Time',
      startJourneyBtn: 'Start My Journey',
    },
  },

  home: {
    greetings: {
      morning: 'Good morning,',
      afternoon: 'Good afternoon,',
      evening: 'Good evening,',
      night: 'Rest well,',
    },
    focusCard: {
      title: 'Today’s Core Focus',
      startBtn: 'Start Session',
      noTaskTitle: 'No priority task is active',
      noTaskSubtitle: 'Set a focus task to start your study timer.',
    },
    stats: {
      focusHours: 'Focus Hours',
      tasksCompleted: 'Tasks Done',
      dayStreak: 'Day Streak',
    },
    schedule: {
      title: 'Next Up Today',
      empty: 'No scheduled routine blocks remaining today.',
      allBlocks: 'View full routine',
    },
    habits: {
      title: 'Daily Habits',
      empty: 'All caught up! No habit checkpoints listed for today.',
    },
    goal: {
      title: 'Active Goal Tracker',
      daysLeft: 'days remaining',
      onTrack: 'On Track',
      atRisk: 'At Risk',
      behind: 'Behind',
    },
    aiCoach: {
      title: 'AI Coach Insight',
    },
  },

  goals: {
    title: 'Goal Vault',
    subtitle: 'Transform grand visions into milestone checklists and daily actions.',
    activeGoals: 'Active Goals',
    completedGoals: 'Achieved Goals',
    addGoal: 'Create New Goal',
    addMilestone: 'Add Milestone',
    addTask: 'Add Task to Milestone',
    swipeToComplete: 'Swipe right to complete',
    swipeToReschedule: 'Swipe left to reschedule',
    reflectionTitle: 'Weekly reflection due',
    reflectionPrompt: 'Sunday 9:00 PM: Write down what went well and where you stumbled.',
  },

  focus: {
    title: 'Deep Work Timer',
    commitLabel: 'What are you focusing on in this block?',
    commitPlaceholder: 'Reading Chapter 4 Organic Chemistry / Drafting business plan...',
    startFocus: 'Start Focus',
    ambientLabel: 'Ambient Soundscape',
    sounds: {
      none: 'Silence',
      rain: 'Gentle Rain',
      cafe: 'Tokyo Café',
      ocean: 'Ocean Breeze',
      lofi: 'Lo-fi Beats',
      noise: 'Brown Noise',
    },
    blockerLabel: 'Deep App Blocker Active',
    blockerLocked: 'Social applications locked securely.',
    iosDisclaimer: 'Uses iOS Screen Time integration. Enable constraints in system settings.',
    summaryTitle: 'Deep Block Complete',
    moodQuestion: 'Rate your focus flow quality during this session:',
    accomplishedLabel: 'What did you accomplish in this session?',
    accomplishedPlaceholder: 'Solved 45 JEE math questions / Outlined landing page design...',
    saveSession: 'Log Focus Session',
  },

  tasks: {
    title: 'Tasks',
    todayTab: 'Today',
    upcomingTab: 'Upcoming',
    completedTab: 'Completed',
    addNewTask: 'New Task',
    taskNamePlaceholder: 'What needs to be done?',
    priorityLabel: 'Priority Tier',
    milestoneLabel: 'Link to Milestone (Optional)',
    recurringLabel: 'Make Task Recurring',
    noTasks: 'No tasks scheduled here.',
  },

  habits: {
    title: 'Habits',
    addHabit: 'Add Custom Habit',
    namePlaceholder: 'Drink 4L Water / Workout...',
    emojiLabel: 'Habit Emoji',
    frequencyLabel: 'Log Frequency',
    currentStreak: 'Current Streak',
    bestStreak: 'All-Time Best',
    logsHeatmap: 'Completion Heatmap',
  },

  learn: {
    title: 'Knowledge Vault',
    tabs: {
      syllabus: 'Syllabus Tracker',
      notes: 'Study Notes',
      flashcards: 'Spaced Flashcards',
    },
    syllabus: {
      searchPlaceholder: 'Search subjects or chapters...',
      bulkAction: 'Batch Update Status',
      topicsCompleted: 'Topics Completed',
      status: {
        not_started: 'Not Started',
        in_progress: 'In Progress',
        done: 'Completed',
        needs_revision: 'Needs Revision',
      },
    },
    notes: {
      placeholderTitle: 'Untitled Note',
      searchPlaceholder: 'Search through notes...',
      autoSaved: 'Saved to cloud atomically',
      spacedRepLabel: 'Due for spaced review today',
    },
    flashcards: {
      swipeInstruction: 'Swipe Right if Memorized, Swipe Left to Cycle Again',
      gotIt: 'Got It!',
      reviewAgain: 'Review Again',
      empty: 'No due flashcards remaining today.',
      congrats: 'Session complete! Spaced repetition schedules updated.',
    },
  },

  stats: {
    title: 'Focus Analytics',
    hoursHeader: 'Focus Allocation',
    heatmapHeader: '90-Day Cognitive Heatmap',
    distributionHeader: 'Subject / Focus Distribution',
    moodHeader: 'Energy & Mood Logs',
    achievementsHeader: 'Earned Badges',
    achievementList: {
      streak30: '30-Day Streak',
      focus100: '100hr Focus Club',
      syllabusCrusher: 'Syllabus Crusher',
      goalAchieved: 'Goal Achiever',
    },
  },

  rooms: {
    title: 'Study Spaces',
    subtitle: 'Sit with aspirants and builders globally in real-time silent accountability.',
    liveStudying: 'studying live right now',
    silentRoom: 'Silent Room 🔇',
    musicRoom: 'Ambient Lofi 🎵',
    discussionRoom: 'Active Discussion 💬',
    joinRoom: 'Join Workspace',
    createRoom: 'Create Study Room',
    membersLabel: 'Aspirants inside',
  },
} as const;

export type AppStrings = typeof STRINGS;
export default STRINGS;
